# The URL the site will be built for
base_url = "https://nilsmango.ch"
title = "Nils Mango"
description = "Creating things & eliminating errors."


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# List of Papaya navigational menu items. Used to construct the navigation bar. See the README for item schema.
menu_items = [
    { name = "Home", url = "/" },
    { name = "About", url = "/about" },
    { name = "Music", url = "/music" },
    { name = "Articles", url = "/articles" },
    { name = "Projects", url = "/about" },
    { name = "Tags", url = "/tags" },
]
